language: cpp
compiler:
- clang
- gcc
os:
- linux
- osx
sudo: false
script:
- make -j4 -f .Makefile check
install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - clang
git:
  submodules: false
branches:
  only:
    - master
